const assert = require('node:assert/strict');
const html = require('node:fs').readFileSync(0, 'utf8');
const elements = new Map();
const el = id => { if (!elements.has(id)) elements.set(id, {}); return elements.get(id); };
const fmtSignedMoney = v => v == null ? 'n/a' : String(v);
const fmtMaybeBps = fmtSignedMoney, fmtMoney = fmtSignedMoney;
let comparison, slippage, rows;
const pnlComparisonSvg = p => {comparison = p; return 'comparison';};
const slippageSvg = p => {slippage = p; return 'slippage';};
const renderExecutionSlippageTable = p => {rows = p;};
const renderMissedOrdersTable = () => {};
let start = html.indexOf('function renderExecutionQuality(payload) {');
eval(html.slice(start, html.indexOf('function renderMissedOrdersTable', start)));
const history = [{as_of:'2026-09-25T23:59:59-04:00',actual_pnl_cnh:'977.08',theoretical_pnl_cnh:'1960.12',execution_gain_cnh:'-983.04'}];
const payload = {as_of:'2026-09-28T23:59:59-04:00',valuation_complete:false,history,
  slippage:[{trade_date:'2026-09-25',daily_slippage_cnh:'-983.01'}],rows:[{symbol:'SPY'}],warnings:['Missing current marks']};
renderExecutionQuality(payload);
assert.equal(el('exec-actual-pnl').textContent,'977.08');
assert.equal(el('exec-bps').textContent,'n/a');
assert.match(el('execution-quality-as-of').textContent,/2026-09-25.*last complete/);
assert.match(el('execution-quality-warnings').textContent,/2026-09-28.*incomplete/);
assert.equal(comparison.length,1);
assert.equal(slippage.length,1);
assert.equal(rows.length,1);
assert.equal(payload.history,history);
renderExecutionQuality({...payload,history:[]});
assert.equal(el('exec-actual-pnl').textContent,'n/a');
assert.equal(slippage.length,1);
renderExecutionQuality({...payload,...history[0],valuation_complete:true,execution_gain_bps:'-11.57'});
assert.equal(el('exec-bps').textContent,'-11.57');
assert.match(el('execution-quality-as-of').textContent,/2026-09-25 close/);
assert.equal(comparison.length,1);
start = html.indexOf('function renderPerformanceDiagnostics(messages) {');
eval(html.slice(start, html.indexOf('function renderPnl', start)));
renderPerformanceDiagnostics(['Research limitations','Research limitations',...Array.from({length:1000},(_,i)=>`Ignored backdated account observation: ${i}.json.`)]);
assert.match(el('performance-warnings').textContent,/Excluded 1000 backdated/);
assert.equal(el('performance-diagnostics-summary').textContent,'Performance notes and data checks (2)');
assert.ok(el('performance-warnings').textContent.length < 250);
assert.match(html,/<details class="performance-diagnostics" id="performance-diagnostics">/);
start = html.indexOf('function pnlComparisonSvg(points, timeline = []) {');
const chart = new Function('fmtSignedMoney','esc','points','timeline',
  html.slice(start,html.indexOf('function slippageSvg(points)',start)) + ';return pnlComparisonSvg(points,timeline);');
const onePoint = chart(fmtSignedMoney,String,history);
assert.equal((onePoint.match(/<circle /g)||[]).length,2);
assert.match(onePoint,/977.08/);
assert.match(onePoint,/1960.12/);
assert.match(html,/execution-quality\?history_limit=100"/);

const marked=chart(fmtSignedMoney,String,[...history,{...history[0],as_of:'2026-09-28'}],[{effective_close:'2026-09-27',label:'60% A + 40% B'}]);
assert.match(marked,/60% A \+ 40% B/);
assert.match(marked,/stroke-dasharray/);
