const assert = require('node:assert/strict');
const html = require('node:fs').readFileSync(0, 'utf8');
const elements = new Map();
const el = id => { if (!elements.has(id)) elements.set(id, {}); return elements.get(id); };
const state = {}, calls = new Map(), rendered = [];
const deferred = () => {
  let resolve, reject;
  const promise = new Promise((a, b) => {resolve = a; reject = b;});
  return {promise, resolve, reject};
};
let performance = deferred(), reconciliation = deferred(), failAttribution = false;
const api = path => {
  calls.set(path, (calls.get(path) || 0) + 1);
  if (path.endsWith('/performance')) return performance.promise;
  if (path.endsWith('/interactive-brokers')) return reconciliation.promise;
  if (path.includes('/pnl/snapshots')) return Promise.reject(new Error('history offline'));
  if (path.includes('/execution-quality') && failAttribution) return Promise.reject(new Error('attribution offline'));
  return Promise.resolve({warnings:[]});
};
const renderAutomation = () => rendered.push('automation');
const renderPerformance = () => rendered.push('performance');
const renderHoldings = () => rendered.push('holdings');
const renderExecutionQuality = () => {rendered.push('attribution'); el('execution-quality-warnings').textContent = '';};
const renderPnl = (pnl, history) => {rendered.push('pnl'); assert.equal(history.length,0); assert.match(pnl.warnings[0], /history offline/);};
const renderReconciliation = () => rendered.push('reconciliation');
const renderReconciliationUnavailable = message => {rendered.push('reconciliation-error'); assert.match(message,/offline/);};
const start = html.indexOf('const dashboardRequests =');
eval(html.slice(start, html.indexOf('function renderReconciliation(payload)', start)));
const flush = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  const first = loadDashboardData(), overlapping = loadDashboardData();
  await flush();
  assert.ok(rendered.includes('attribution'));
  assert.ok(rendered.includes('pnl'));
  assert.ok(!rendered.includes('performance'));
  assert.ok([...calls.values()].every(count => count === 1));
  performance.reject(new Error('performance offline'));
  reconciliation.reject(new Error('gateway offline'));
  await Promise.all([first, overlapping]);
  assert.match(el('performance-warnings').textContent, /Refresh failed/);
  assert.equal(state.reconciliation.unavailable, true);
  failAttribution = true;
  await loadDashboardData();
  assert.match(el('execution-quality-warnings').textContent, /attribution offline/);
  performance = {promise:Promise.resolve({})};
  reconciliation = {promise:Promise.resolve({})};
  failAttribution = false;
  await loadDashboardData();
  assert.ok(rendered.includes('performance'));
  assert.equal(el('execution-quality-warnings').textContent, '');
})().catch(error => {console.error(error); process.exitCode=1;});
